USE ccrep;

GO

DROP VIEW out.OUT_CCREP_CLIENT_ACCOUNT 
DROP VIEW out.OUT_CCREP_CODE_405_SETTINGS
DROP VIEW out.OUT_CCREP_CUSTOMER_ACCOUNTS  
DROP VIEW out.OUT_CCREP_KEYWORDS
DROP VIEW out.OUT_CCREP_KEYWORDS_EXСEPTION
DROP VIEW out.OUT_CCREP_LOG

-- GO

-- DROP SCHEMA out

GO
