CREATE VIEW out.OUT_CCREP_CLIENT_ACCOUNT (ID_KEY, ACC_NO, CNUM) 
AS
SELECT ID_KEY, CBACCOUNT, CNUM
FROM DIC_ACCOUNT_CLIENT
WHERE (END_DATE is NULL) OR 
(CAST(END_DATE as datetime) <= CAST(FLOOR(CAST(GETDATE() as float)) as datetime))
