CREATE VIEW out.OUT_CCREP_KEYWORDS (ID_KEY, KEYWORD_TXT) 
AS
SELECT ID_KEY, KEYWORD
FROM DIC_KEYWORDS WHERE (END_DATE is NULL) OR 
(CAST(END_DATE as datetime) <= CAST(FLOOR(CAST(GETDATE() as float)) as datetime))